spring:
  application:
    name: eng-learn-app
  datasource:
    url: jdbc:postgresql://localhost:5433/eng_learn_db
    username: postgres
    password: muliko08m
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

logging:
  level:
    org.flywaydb: DEBUG