  spring.application.name=eng-learn-app

spring:
  application:
    name: eng-learn-app
  datasource:
    url: jdbc:postgresql://localhost:5432/eng_learn_db
    username: postgres
    password: muliko08m
    driver-class-name: org.postgresql.Driver

  spring:
    application:
      name: eng-learn-app
    datasource:
      url: jdbc:h2:mem:eng-learn-appdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: muliko08m

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:/migrations
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

logging:
  level:
    org.flywaydb: DEBUG